# Generated by Django 5.0.7 on 2024-07-28 13:29

from django.db import migrations

def add_product_data(apps, schema_editor):
    ProductCategory = apps.get_model('client', 'ProductCategory')
    ProductSubcategory = apps.get_model('client', 'ProductSubcategory')
    Product = apps.get_model('client', 'Product')

    # Create categories
    aquariums_cat = ProductCategory.objects.create(name='Aquariums')
    equipment_cat = ProductCategory.objects.create(name='Equipment')
    decorations_cat = ProductCategory.objects.create(name='Decorations')

    # Create subcategories
    nano_subcat = ProductSubcategory.objects.create(name='Nano Aquariums', category=aquariums_cat)
    beginner_subcat = ProductSubcategory.objects.create(name='Beginner Aquariums', category=aquariums_cat)
    reef_ready_subcat = ProductSubcategory.objects.create(name='Reef-ready Aquariums', category=aquariums_cat)

    filters_subcat = ProductSubcategory.objects.create(name='Filters', category=equipment_cat)
    heaters_subcat = ProductSubcategory.objects.create(name='Heaters', category=equipment_cat)
    lighting_subcat = ProductSubcategory.objects.create(name='Lighting', category=equipment_cat)

    ornaments_subcat = ProductSubcategory.objects.create(name='Ornaments', category=decorations_cat)
    substrate_subcat = ProductSubcategory.objects.create(name='Substrate', category=decorations_cat)
    driftwood_subcat = ProductSubcategory.objects.create(name='Driftwood', category=decorations_cat)

    # Create products
    Product.objects.create(
        name='Nano Cube 10G',
        description='A 10-gallon nano aquarium perfect for small spaces.',
        price=150.00,
        reference='NC-10G',
        brand='AquaDream',
        category=aquariums_cat,
        subcategory=nano_subcat
    )
    Product.objects.create(
        name='Beginner Aquarium Kit 20G',
        description='All-in-one 20-gallon aquarium kit for beginners.',
        price=250.00,
        reference='BAK-20G',
        brand='EasyLife',
        category=aquariums_cat,
        subcategory=beginner_subcat
    )
    Product.objects.create(
        name='Reef-Ready Aquarium 120G',
        description='A 120-gallon reef-ready aquarium with built-in overflow.',
        price=1200.00,
        reference='RRA-120G',
        brand='Oceanic',
        category=aquariums_cat,
        subcategory=reef_ready_subcat
    )
    Product.objects.create(
        name='QuietFlow Canister Filter',
        description='A silent and powerful canister filter for aquariums up to 75 gallons.',
        price=180.00,
        reference='QFCF-75G',
        brand='AquaTech',
        category=equipment_cat,
        subcategory=filters_subcat
    )
    Product.objects.create(
        name='Submersible Aquarium Heater 100W',
        description='A 100-watt submersible heater for aquariums up to 30 gallons.',
        price=35.00,
        reference='SAH-100W',
        brand='ThermoGuard',
        category=equipment_cat,
        subcategory=heaters_subcat
    )
    Product.objects.create(
        name='LED Aquarium Light 36"',
        description='A 36-inch LED light with full spectrum for plant growth.',
        price=90.00,
        reference='LAL-36',
        brand='Luminar',
        category=equipment_cat,
        subcategory=lighting_subcat
    )
    Product.objects.create(
        name='Sunken Ship Ornament',
        description='A realistic sunken ship ornament for your aquarium.',
        price=25.00,
        reference='SSO-01',
        brand='DecoReef',
        category=decorations_cat,
        subcategory=ornaments_subcat
    )
    Product.objects.create(
        name='Black Diamond Sand 20lb',
        description='20 lbs of black diamond sand for a stunning aquarium substrate.',
        price=30.00,
        reference='BDS-20LB',
        brand='NatureSubstrate',
        category=decorations_cat,
        subcategory=substrate_subcat
    )
    Product.objects.create(
        name='Malaysian Driftwood Large',
        description='A large piece of Malaysian driftwood to create a natural look.',
        price=45.00,
        reference='MDL-01',
        brand='TerraWood',
        category=decorations_cat,
        subcategory=driftwood_subcat
    )
    Product.objects.create(
        name='Floating Log',
        description='A floating log for your fish to hide and play in.',
        price=15.00,
        reference='FL-01',
        brand='AquaDecor',
        category=decorations_cat,
        subcategory=ornaments_subcat
    )

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_product_data),
    ]