# Generated by Django 5.2.6 on 2025-12-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_maincarousel_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDailyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_promotion', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_monthly', models.BooleanField(default=False)),
                ('is_daily', models.BooleanField(default=False)),
                ('deal_start', models.DateTimeField(blank=True, null=True)),
                ('deal_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='MonthlyDailyDeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.monthlydailydeal'),
        ),
    ]
