# Generated by Django 5.2.6 on 2025-10-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_style', models.CharField(choices=[('default', 'Default'), ('golden', '    Golden'), ('green', 'Green'), ('dark', 'Dark')], default='default', max_length=20)),
            ],
        ),
    ]
