# Generated by Django 5.2.6 on 2025-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_style', models.CharField(choices=[('default', 'Default'), ('golden', 'Golden'), ('green', 'Green'), ('dark', 'Dark')], default='default', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='NavbarControl',
        ),
    ]
