# Generated by Django 5.2.6 on 2025-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_adminuiconfig_delete_navbarcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuiconfig',
            name='navbar_style',
            field=models.CharField(choices=[('defaut', 'Default'), ('golden', 'Golden'), ('green', 'Green'), ('dark', 'Dark')], default='defaut', max_length=20),
        ),
    ]
