"""
Django settings for aquatiako project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c%3k&12vgj8yo#iafmk+!weog(gu=c6pjzm$zrro%kyq=59dc4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'client',
    'backend',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aquatiako.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'client.context_processors.categories_processor',
                'backend.context_processors.global_navbar_style',
            ],
        },
    },
]

WSGI_APPLICATION = 'aquatiako.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # ✅ Use MySQL backend
        'NAME': 'aquatiako',           # Replace with your DB name
        'USER': 'root',              # Replace with your MySQL username
        'PASSWORD': '15lpq32x',      # Replace with your MySQL password
        'HOST': 'localhost',                    # Or your DB server IP
        'PORT': '3306',                         # Default MySQL port
    }
}





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
     {
         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR/'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'client/static', BASE_DIR / 'backend/static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL to redirect to after a user successfully logs in.
# In this case, it redirects to the '/admin_panel/' URL.
LOGIN_REDIRECT_URL = '/admin_panel/'

# URL to redirect to after a user logs out.
# In this case, it redirects to the '/admin_panel/login' URL.
LOGOUT_REDIRECT_URL = '/admin_panel/login'

# URL where the login page is located.
# Django's authentication system will redirect unauthenticated users to this URL.
# In this case, it's set to '/admin_panel/login/'.
LOGIN_URL = '/admin_panel/login/'

# This is a duplicate of the LOGOUT_REDIRECT_URL above.
# It specifies the URL to redirect to after a user logs out.
# In this case, it's also set to '/admin_panel/login/'.
LOGOUT_REDIRECT_URL = '/admin_panel/login/'



ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "kbgyz-129-222-109-140.a.free.pinggy.link"
    
]
